version: '3.4'

services:

  grafana:
    image: grafana/grafana:10.2.9
    restart: always
    container_name: booq_grafana
#    env_file:
#      - 'env.grafana'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=logmon
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
    ports:
#      - 127.0.0.1:3000:3000
      - 3000:3000
    volumes:
#      - /opt/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    labels:
      container_group: logging
    networks:
      - mon_net

networks:
  mon_net:
   external:
    name: monitoring_default
